### ISSUE TITLE
name 'token' is not defined

### ISSUE THREAD

**Issue by darksetyaer** [Upsetin/ChinaUniOnline#100]
# 请求帮助

## 正常运行
我输入uid后运行不了，但在exe中文件执行同样的操作是没有出错的，报错信息如下，大佬们看看有什么问题
Traceback (most recent call last):
  File "D:\ChinaUniOnline-main\main.py", line 469, in <module>
    info = GetInfo()
  File "D:\ChinaUniOnline-main\main.py", line 25, in GetInfo
    'authorization': 'Bearer %s' % (token),
NameError: name 'token' is not defined

**Comment by arenekosreal** [comment]
出错之前输出内容是否提到了获取token的状态？是已获取token还是获取失败？

**Comment by darksetyaer** [comment]
> 出错之前输出内容是否提到了获取token的状态？是已获取token还是获取失败？

正在获取token，请稍后...
uid输入有误或网络问题...
token已更新...

**Comment by arenekosreal** [comment]
> > 出错之前输出内容是否提到了获取token的状态？是已获取token还是获取失败？
> 
> 正在获取token，请稍后...
> uid输入有误或网络问题...
> token已更新...

用uid获取token失败了，dalao没做错误处理，程序就继续运行了。因为没有获取到token，这个变量自然就未初始化了，调用这个变量就会失败

**Comment by arenekosreal** [comment]
可以到脚本381行插入`print(a.json())`然后把新增加的那个输出发一下吗

**Comment by darksetyaer** [comment]
正在获取token，请稍后...
uid输入有误或网络问题...
token已更新...
Traceback (most recent call last):
  File "D:\ChinaUniOnline-main\main.py", line 470, in <module>
    info = GetInfo()
  File "D:\ChinaUniOnline-main\main.py", line 25, in GetInfo
    'authorization': 'Bearer %s' % (token),
NameError: name 'token' is not defined

**Comment by darksetyaer** [comment]
> 可以到脚本381行插入`print(a.json())`然后把新增加的那个输出发一下吗

突然就更新好了，谢谢大佬，但它现在好像又找不到题库了，信息如下
Traceback (most recent call last):
  File "D:\ChinaUniOnline-main\main.py", line 486, in <module>
    GetQuestions()
  File "D:\ChinaUniOnline-main\main.py", line 119, in GetQuestions
    if GetOption(activity_id=activity_id,question_id=question_ids[i],mode_id=mode_id):
  File "D:\ChinaUniOnline-main\main.py", line 180, in GetOption
    db = ReadFile()
  File "D:\ChinaUniOnline-main\main.py", line 64, in ReadFile
    with open("题库.csv", "r",encoding='UTF-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '题库.csv'

**Comment by arenekosreal** [comment]
那就可能是服务器请求过程的问题了，请到472行把`except:`改成`except Exception as e:`并在下一行加入`print(e)`来看看具体错误内容是什么。注意`print(e)`是`except`的子代码块，缩进是和`judge = False`同级的

**Comment by arenekosreal** [comment]
> > 可以到脚本381行插入`print(a.json())`然后把新增加的那个输出发一下吗
> 
> 突然就更新好了，谢谢大佬，但它现在好像又找不到题库了，信息如下
> Traceback (most recent call last):
>   File "D:\ChinaUniOnline-main\main.py", line 486, in <module>
>     GetQuestions()
>   File "D:\ChinaUniOnline-main\main.py", line 119, in GetQuestions
>     if GetOption(activity_id=activity_id,question_id=question_ids[i],mode_id=mode_id):
>   File "D:\ChinaUniOnline-main\main.py", line 180, in GetOption
>     db = ReadFile()
>   File "D:\ChinaUniOnline-main\main.py", line 64, in ReadFile
>     with open("题库.csv", "r",encoding='UTF-8') as f:
> FileNotFoundError: [Errno 2] No such file or directory: '题库.csv'

你在编辑器里面启动的脚本吗？请手动在脚本文件夹下打开终端启动。编辑器提供的终端环境的工作目录不一定是脚本文件夹

**Comment by darksetyaer** [comment]
> > > 可以到脚本381行插入`print(a.json())`然后把新增加的那个输出发一下吗
> > 
> > 
> > 突然就更新好了，谢谢大佬，但它现在好像又找不到题库了，信息如下
> > Traceback (most recent call last):
> > File "D:\ChinaUniOnline-main\main.py", line 486, in 
> > GetQuestions()
> > File "D:\ChinaUniOnline-main\main.py", line 119, in GetQuestions
> > if GetOption(activity_id=activity_id,question_id=question_ids[i],mode_id=mode_id):
> > File "D:\ChinaUniOnline-main\main.py", line 180, in GetOption
> > db = ReadFile()
> > File "D:\ChinaUniOnline-main\main.py", line 64, in ReadFile
> > with open("题库.csv", "r",encoding='UTF-8') as f:
> > FileNotFoundError: [Errno 2] No such file or directory: '题库.csv'
> 
> 你在编辑器里面启动的脚本吗？请手动在脚本文件夹下打开终端启动。编辑器提供的终端环境的工作目录不一定是脚本文件夹

我用cmd启动的

**Comment by arenekosreal** [comment]
那也得检查一下cmd的工作目录是不是脚本文件夹，也许我应该像gui程序一样加一个自动切换工作目录到脚本文件夹的能力

**Comment by darksetyaer** [comment]
> 那也得检查一下cmd的工作目录是不是脚本文件夹，也许我应该像gui程序一样加一个自动切换工作目录到脚本文件夹的能力

解决了，谢谢大佬，感谢感谢

**Comment by arenekosreal** [comment]
解决了麻烦关一下这个问题。
