### ISSUE TITLE
官方更新

### ISSUE THREAD

**Issue by SDS01** [Upsetin/ChinaUniOnline#103]
# 请求帮助
今晚更新了，还有什么办法吗
## 目标

[^_^]: 在这里写你想做什么
xxxxxx

**Comment by arenekosreal** [comment]
gui脚本已更新，原版程序无影响

**Comment by arenekosreal** [comment]
解决了问题请点一下Close issue关闭这个问题

**Comment by SDS01** [comment]
> 解决了问题请点一下Close issue关闭这个问题

今天开始封号了，怎么办好几，有什么办法吗，可以解封吗

**Comment by arenekosreal** [comment]
服务器行为，目前客户端这边肯定解不掉。有说法是修改传输数据向服务器提交一个新的uid就可以继续用了

**Comment by SDS01** [comment]
> 服务器行为，目前客户端这边肯定解不掉。有说法是修改传输数据向服务器提交一个新的uid就可以继续用了
那这个软件还可以用吗，会封号吗

**Comment by arenekosreal** [comment]
> > 服务器行为，目前客户端这边肯定解不掉。有说法是修改传输数据向服务器提交一个新的uid就可以继续用了
> 那这个软件还可以用吗，会封号吗
> 

用是可以用，这种脚本我只能说用别怂，怂别用。总归不是正常答题，封号总是有概率的

**Comment by SDS01** [comment]
> > > 服务器行为，目前客户端这边肯定解不掉。有说法是修改传输数据向服务器提交一个新的uid就可以继续用了
> > > 那这个软件还可以用吗，会封号吗
> 
> 用是可以用，这种脚本我只能说用别怂，怂别用。总归不是正常答题，封号总是有概率的

明白了

**Comment by arenekosreal** [comment]
解决了问题就麻烦关闭这个问题

**Comment by BiiiGerrr** [comment]
> 服务器行为，目前客户端这边肯定解不掉。有说法是修改传输数据向服务器提交一个新的uid就可以继续用了

求问dalao，怎么提交新的uid

**Comment by arenekosreal** [comment]
> > 服务器行为，目前客户端这边肯定解不掉。有说法是修改传输数据向服务器提交一个新的uid就可以继续用了
> 
> 求问dalao，怎么提交新的uid

大概过程是抓包工具拦截正常请求，修改请求数据里面的UID，然后重新发送这个拦截的请求。具体咋做我也没试过
