### ISSUE TITLE
脚本疑似失效

### ISSUE THREAD

**Issue by Chenx221** [Upsetin/ChinaUniOnline#105]
# Bug报告

## 脚本类型

[^_^]:使用的是原版还是GUI版本  
原版

## 问题描述

[^_^]:遇到了什么问题
两个账号刷题都报错了（其中有一个新号

## Python版本

[^_^]:正在使用的Python版本及架构
Python 3.7.3 (default, Jan 22 2021, 20:04:44)

## Pip安装的软件包

```text
Package       Version
------------- ---------
asn1crypto    0.24.0
certifi       2020.12.5
chardet       4.0.0
cryptography  2.6.1
entrypoints   0.3
idna          2.10
keyring       17.1.1
keyrings.alt  3.1.1
pip           18.1
pycrypto      2.6.1
PyGObject     3.30.4
pyxdg         0.25
requests      2.25.1
SecretStorage 2.3.1
setuptools    40.8.0
six           1.12.0
urllib3       1.26.4
wheel         0.32.3
 
```

## 操作系统

[^_^]:是Windows还是Linux或者OSX以及是32位系统还是64位系统
Debian 10

## 终端输出  

```shell

英雄篇-正在第1次刷题～
Traceback (most recent call last):
  File "main.py", line 485, in <module>
    GetQuestions()
  File "main.py", line 107, in GetQuestions
    question_ids = response.json()['question_ids']
KeyError: 'question_ids'


```

![Screenshot_20210419_112314.jpg](https://user-images.githubusercontent.com/21092976/115178042-02454500-a103-11eb-946a-f8b600cbcdff.jpg)

**Comment by arenekosreal** [comment]
看一下107行那个response的内容，这看起来似乎是没有成功获取到题目列表

**Comment by Chenx221** [comment]
😂进答题系统里看了眼，提示账号被禁用了
看来是翻车了

**Comment by arenekosreal** [comment]
啊这。。。找转生的路子吧😂
有办法用这个微信刷一个新的uid，不过我没有试。

**Comment by jllobvemy** [comment]
这会不能刷了，官方把答题入口关了，还在答题的直接封，钓鱼执法

**Comment by jllobvemy** [comment]
建议说明一下

**Comment by Chenx221** [comment]
> 啊这。。。找转生的路子吧😂
> 有办法用这个微信刷一个新的uid，不过我没有试。

能说说具体方法吗

**Comment by XCY6216** [comment]
> 这会不能刷了，官方把答题入口关了，还在答题的直接封，钓鱼执法

封号的还能解开吗？

**Comment by arenekosreal** [comment]
> > 啊这。。。找转生的路子吧😂
> > 有办法用这个微信刷一个新的uid，不过我没有试。
> 
> 能说说具体方法吗

公众号i呀我去有详细办法
https://mp.weixin.qq.com/s/RiWzaIYvanW80ppOgVlwKg

**Comment by Chenx221** [comment]
换来的新uid貌似不能用脚本刷题
接下来要手动答题了😂

**Comment by arenekosreal** [comment]
> 换来的新uid貌似不能用脚本刷题
> 接下来要手动答题了😂

有很多人刷了新uid之后依然在用脚本刷，不过我这个账号还活着所以没有去试。
另外看截图在用Termux？可以直接在里面装Python运行脚本，不用再启动一个Linux文件系统这么麻烦

**Comment by Chenx221** [comment]
？？昨天被封的几个账号貌似解封了，积分都还在
可以正常答题，但貌似一使用原版脚本就会追封（小号中招,大号不敢试了
登上去时可以显示积分，但一开刷就封号...
