### ISSUE TITLE
小白思路（最近的问题）

### ISSUE THREAD

**Issue by by7741** [Upsetin/ChinaUniOnline#110]
就是目前为止，已现有的登录方式是可以登录，但是一开始运行答题程序之后，就会闪退，手动进入公众号后，会提示账户被禁用，看到代码里显示，应该是获取题目那里出了问题，因为是小白一个，没有基础，看不懂，现在只要是开始就是秒封禁账户，希望可以更新一下

**Comment by by7741** [comment]
![EE99451C-4ED9-4107-A779-28E132D51A49](https://user-images.githubusercontent.com/38809940/115484634-b242bb80-a285-11eb-84cb-20c3667454f3.png)
补充一下png

**Comment by arenekosreal** [comment]
可以试试GUI程序吗？我想看看这是原版程序独有的问题还是用转生账号都会出现的问题

**Comment by by7741** [comment]
> 可以试试GUI程序吗？ 我想看看这是原版程序独有的问题还是用转生账号都会出现的问题

GUI程序可以使用，只是单独对于main.py程序的问题

**Comment by arenekosreal** [comment]
> > 可以试试 GUI 程序吗？ 我想看看这是原版程序独有的问题还是用转生账号都会出现的问题
> 
> GUI 程序可以使用，只是单独对于 main.py 程序的问题

那应该就是原版程序部分信息写死在脚本里面导致的。我这几天有点忙，估计得等几天把GUI的随机化移植一下，或者等dalao来搞。这几天麻烦用GUI应一下急吧。另外GUI默认的延迟有点短，为了稳妥，建议按照 https://github.com/Upsetin/ChinaUniOnline/issues/106 这里面讲的手动提高一下延迟，减少爆破概率
@Upsetin dalao麻烦了
