### ISSUE TITLE
封号问题

### ISSUE THREAD

**Issue by yeedo-sec** [Upsetin/ChinaUniOnline#114]
用之前脚本一跑就封号了现在，作者大大能具体讲讲这个转生账号的操作吗

**Comment by arenekosreal** [comment]
https://mp.weixin.qq.com/s/RiWzaIYvanW80ppOgVlwKg
看这个文章，大概过程就是用公众号提供的工具，点几下就行。因为我的账号没有封号，所以具体啥样我也没有亲自试过😂
https://github.com/Upsetin/ChinaUniOnline/issues/106
这是一些额外的注意事项

**Comment by arenekosreal** [comment]
解决了问题麻烦点一下Close issue关闭这个问题
