### ISSUE TITLE
GUI模式下start.vbs运行错误的问题

### ISSUE THREAD

**Issue by Dawnwalker666** [Upsetin/ChinaUniOnline#118]
# 请求帮助

## 目标

因为通过  i呀我去  的公众号获取新的uid ，会积分清零。而我们学校又要几千分截图上交。因此就不得不尝试GUI模式。
RT，我已经安装好了requirements。但是在运行start.vbs时候，会弹出这个界面。
![QQ截图20210423125706](https://user-images.githubusercontent.com/49862610/115820875-4b173980-a434-11eb-8750-fac69ce58108.png)
请问这是什么原因导致的？需要我做什么才能运行？

**Comment by Dawnwalker666** [comment]
另外就是，直接运行 main-gui.py 文件，会突闪出一个黑色cmd窗口然后消失。就像什么也没发生过一样。

**Comment by arenekosreal** [comment]
试试手动在终端切换到GUI文件夹，运行`pythonw main-gui.py`看看能不能启动

**Comment by Dawnwalker666** [comment]
![QQ截图20210423134116](https://user-images.githubusercontent.com/49862610/115823852-a992e680-a439-11eb-9636-4bedc0f0071c.png)
不能

**Comment by arenekosreal** [comment]
那么运行`python main-gui.py`的输出是什么

**Comment by arenekosreal** [comment]
还有，你刚刚那个终端似乎不在GUI文件夹，而在GUI的上层

**Comment by Dawnwalker666** [comment]
> 
> 
> 还有，你刚刚那个终端似乎不在GUI文件夹，而在GUI的上层

是我的失误。运行  pythonw main-gui.py  可以启动。多谢
