### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by H0121** [Upsetin/ChinaUniOnline#121]
用打包文件登 闪退 用pycharm登 报32行的headers里的token找不到的错误

**Comment by arenekosreal** [comment]
看起来像是没拿到token，试试`main.py`或者GUI版本有没有问题，exe文件没有更新

**Comment by H0121** [comment]
main.py的问题就是token没找到

**Comment by H0121** [comment]
> 看起来像是没拿到token，试试`main.py`或者GUI版本有没有问题，exe文件没有更新

main.py的问题就是32行的token没找到

**Comment by arenekosreal** [comment]
那试试GUI有没有这个问题呢？

**Comment by H0121** [comment]
> 那试试GUI有没有这个问题呢？

也不行 直接程序停止运行

**Comment by arenekosreal** [comment]
可以在终端下切换到gui文件夹，手动执行`python main-gui.py`看看具体的错误是啥，这个情况看起来像是无法和服务器连接。

**Comment by snfcx** [comment]
@zhanghua000 gui生成题库时未响应卡死了，请问题库是要自己刷题慢慢完善吗？有没有完成了的题库文件呀？谢谢！

**Comment by snfcx** [comment]
> @zhanghua000 gui生成题库时未响应卡死了，请问题库是要自己刷题慢慢完善吗？有没有完成了的题库文件呀？谢谢！

而且自己刷题完善发现好像并没有成功把题目储存。是刷一会闪退程序没有保存的原因吗

**Comment by arenekosreal** [comment]
没保存是因为程序崩了。生成题库这个有问题的话按照Tools文件夹的描述导入原版程序的题库吧，我空下来了看一下为什么会卡死

**Comment by H0121** [comment]
> 可以在终端下切换到gui文件夹，手动执行`python main-gui.py`看看具体的错误是啥，这个情况看起来像是无法和服务器连接。

还是不行 token变量找不到是为啥

**Comment by arenekosreal** [comment]
> > 可以在终端下切换到gui文件夹，手动执行`python main-gui.py`看看具体的错误是啥，这个情况看起来像是无法和服务器连接。
> 
> 还是不行 token变量找不到是为啥

终端输出是什么呢

**Comment by snfcx** [comment]
> > > 可以在终端下切换到gui文件夹，手动执行`python main-gui.py`看看具体的错误是啥，这个情况看起来像是无法和服务器连接。
> > 
> > 
> > 还是不行 token变量找不到是为啥
> 
> 终端输出是什么呢

![image](https://user-images.githubusercontent.com/55078254/116418243-88355e80-a86e-11eb-85e2-dd280d16c9b0.png)
突然出现这个之后闪退，和运行次数完了也会闪退

**Comment by arenekosreal** [comment]
> @zhanghua000 gui 生成题库时未响应卡死了，请问题库是要自己刷题慢慢完善吗？有没有完成了的题库文件呀？谢谢！

我现在已经更新了一个文件在我的fork，地址是 https://github.com/zhanghua000/ChinaUniOnline ，应该能正常生成题库了。麻烦测试一下。要是没有问题的话我就提一个pull requests合并进这个存储库

**Comment by arenekosreal** [comment]
> > > > 可以在终端下切换到 gui 文件夹，手动执行 `python main-gui.py` 看看具体的错误是啥，这个情况看起来像是无法和服务器连接。
> > > 
> > > 
> > > 还是不行 token 变量找不到是为啥
> > 
> > 
> > 终端输出是什么呢
> 
> ![image](https://user-images.githubusercontent.com/55078254/116418243-88355e80-a86e-11eb-85e2-dd280d16c9b0.png)
> 突然出现这个之后闪退，和运行次数完了也会闪退

这里指的终端输出是运行`python main-gui.py`的那个黑乎乎的窗口给出的输出，不是这个日志窗口给的输出。

**Comment by snfcx** [comment]
> > @zhanghua000 gui 生成题库时未响应卡死了，请问题库是要自己刷题慢慢完善吗？有没有完成了的题库文件呀？谢谢！
> 
> 我现在已经更新了一个文件在我的fork，地址是 https://github.com/zhanghua000/ChinaUniOnline ，应该能正常生成题库了。麻烦测试一下。要是没有问题的话我就提一个pull requests合并进这个存储库

可以了没有问题，但是运行久了还是会闪退导致没有储存题库，是否可以每储存一条自动保存？

**Comment by snfcx** [comment]
> > > @zhanghua000 gui 生成题库时未响应卡死了，请问题库是要自己刷题慢慢完善吗？有没有完成了的题库文件呀？谢谢！
> > 
> > 
> > 我现在已经更新了一个文件在我的fork，地址是 https://github.com/zhanghua000/ChinaUniOnline ，应该能正常生成题库了。麻烦测试一下。要是没有问题的话我就提一个pull requests合并进这个存储库
> 
> 可以了没有，但是运行久了还是会闪退导致没有储存题库，是否可以每储存一条自动保存？

前面是可以了没有问题，少打了emmm

**Comment by arenekosreal** [comment]
> > > @zhanghua000 gui 生成题库时未响应卡死了，请问题库是要自己刷题慢慢完善吗？有没有完成了的题库文件呀？谢谢！
> > 
> > 
> > 我现在已经更新了一个文件在我的 fork，地址是 https://github.com/zhanghua000/ChinaUniOnline ，应该能正常生成题库了。麻烦测试一下。要是没有问题的话我就提一个 pull requests 合并进这个存储库
> 
> 可以了没有问题，但是运行久了还是会闪退导致没有储存题库，是否可以每储存一条自动保存？

能够帮忙看一下闪退的错误追踪吗？需要手动在终端切换到GUI文件夹，执行`python main-gui.py`

**Comment by snfcx** [comment]
> > > > @zhanghua000 gui 生成题库时未响应卡死了，请问题库是要自己刷题慢慢完善吗？有没有完成了的题库文件呀？谢谢！
> > > 
> > > 
> > > 我现在已经更新了一个文件在我的 fork，地址是 https://github.com/zhanghua000/ChinaUniOnline ，应该能正常生成题库了。麻烦测试一下。要是没有问题的话我就提一个 pull requests 合并进这个存储库
> > 
> > 
> > 可以了没有问题，但是运行久了还是会闪退导致没有储存题库，是否可以每储存一条自动保存？
> 
> 能够帮忙看一下闪退的错误追踪吗？需要手动在终端切换到GUI文件夹，执行`python main-gui.py`

![image](https://user-images.githubusercontent.com/55078254/116493334-13dfd700-a8d1-11eb-93af-77f6fffb1c8f.png)
![image](https://user-images.githubusercontent.com/55078254/116493627-b009de00-a8d1-11eb-8542-e70fe763b585.png)

是这个吗？中途闪退好像是pycharm的问题，用自带的环境运行没有这个情况。不过在执行完成后会像上图一样。重新获取用户信息的过程中闪退，数据库文件保存了上一分钟的到answers.db-journal这个文件里了

**Comment by arenekosreal** [comment]
> > > > > @zhanghua000 gui 生成题库时未响应卡死了，请问题库是要自己刷题慢慢完善吗？有没有完成了的题库文件呀？谢谢！
> > > > 
> > > > 
> > > > 我现在已经更新了一个文件在我的 fork，地址是 https://github.com/zhanghua000/ChinaUniOnline ，应该能正常生成题库了。麻烦测试一下。要是没有问题的话我就提一个 pull requests 合并进这个存储库
> > > 
> > > 
> > > 可以了没有问题，但是运行久了还是会闪退导致没有储存题库，是否可以每储存一条自动保存？
> > 
> > 能够帮忙看一下闪退的错误追踪吗？需要手动在终端切换到GUI文件夹，执行`python main-gui.py`
> 
> ![image](https://user-images.githubusercontent.com/55078254/116493334-13dfd700-a8d1-11eb-93af-77f6fffb1c8f.png)
> ![image](https://user-images.githubusercontent.com/55078254/116493627-b009de00-a8d1-11eb-8542-e70fe763b585.png)
> 
> 是这个吗？中途闪退好像是pycharm的问题，用自带的环境运行没有这个情况。不过在执行完成后会像上图一样。重新获取用户信息的过程中闪退，数据库文件保存了上一分钟的到answers.db-journal这个文件里了

服务器返回的用户信息不对，看看你这个账号是不是可以在微信正常用，如果可以的话请在设置里面打开调试模式，并提供脚本第461行的json_response的内容（直接把第469行的内容移到第461行下面就行了）

**Comment by H0121** [comment]
![Uploading PI}MPDAFU53%(DF36G@LCMJ.png…]()

**Comment by H0121** [comment]
无法找到token
![问题](https://user-images.githubusercontent.com/66578388/117527912-f82bad80-b001-11eb-87f4-18cf02dec677.png)
