### ISSUE TITLE
请问GUI版现在稳吗

### ISSUE THREAD

**Issue by Oopas** [Upsetin/ChinaUniOnline#122]
RT

**Comment by arenekosreal** [comment]
自己把提交的延迟调好就没问题，目前为止我这里可以正常使用全部的功能

**Comment by Oopas** [comment]
> 自己把提交的延迟调好就没问题，目前为止我这里可以正常使用全部的功能

已经安装了依赖了但是提示
`This application failed to start because no QT platform plugin could be initialized`
QT6看起来是安装了的。。

**Comment by arenekosreal** [comment]
这个问题是因为PyQt安装不完整，需要卸载后重装。如果这个问题仍然存在，请使用一个干净的Python环境（virtual env也行）运行脚本

**Comment by Oopas** [comment]
> 这个问题是因为PyQt安装不完整，需要卸载后重装。如果这个问题仍然存在，请使用一个干净的Python环境（virtual env也行）运行脚本

好使了
谢谢
