### ISSUE TITLE
GUI打开报错

### ISSUE THREAD

**Issue by Fyx2002** [Upsetin/ChinaUniOnline#127]
# Bug报告

## 脚本类型

GUI

## 问题描述

运行报错

## Python版本

python 3.9.5

## Pip安装的软件包

asgiref         3.3.4
beautifulsoup4  4.9.3
certifi         2020.12.5
chardet         4.0.0
cycler          0.10.0
Django          3.2.2
django-tinymce  3.3.0
idna            2.10
kiwisolver      1.3.1
matplotlib      3.4.2
numpy           1.20.2
pillow          8.2.0
pip             21.1.1
pycryptodome    3.10.1
pyparsing       2.4.7
PyQt6           6.0.3
PyQt6-Qt6       6.0.2
PyQt6-sip       13.0.1
PySocks         1.7.1
python-dateutil 2.8.1
pytz            2021.1
requests        2.25.1
setuptools      56.0.0
six             1.15.0
soupsieve       2.2.1
sqlparse        0.4.1
tenacity        7.0.0
urllib3         1.26.4

## 操作系统

windows 10 ltsc x64

## 终端输出  

Traceback (most recent call last):
  File "E:\Tools\ChinaUniOnline-main\GUI\main-gui.py", line 15, in <module>
    from matplotlib import pyplot as plt
  File "D:\Program Files\Python39\lib\site-packages\matplotlib\__init__.py", line 107, in <module>
    from . import _api, cbook, docstring, rcsetup
  File "D:\Program Files\Python39\lib\site-packages\matplotlib\rcsetup.py", line 24, in <module>
    from matplotlib import _api, animation, cbook
  File "D:\Program Files\Python39\lib\site-packages\matplotlib\animation.py", line 34, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'

## 日志文件

```text

在这里粘贴调试模式（设置里面打开）日志文件内容，替换这一行文字


```

**Comment by arenekosreal** [comment]
pillow没装对？ 
用PyCharm运行的话在它的包管理器里面添加Pillow，直接运行的话就重装一下Pillow

**Comment by Fyx2002** [comment]
问题解决
