### ISSUE TITLE
QT版本问题

### ISSUE THREAD

**Issue by Believeht029** [Upsetin/ChinaUniOnline#128]
# 请求帮助
![image](https://user-images.githubusercontent.com/45315146/119252227-a0826a00-bbdd-11eb-9faa-9398bcf48082.png)

**Comment by arenekosreal** [comment]
用的是PyQt6，不要装成PyQt5了

**Comment by Believeht029** [comment]
就是用的PyQt6啊
![image](https://user-images.githubusercontent.com/45315146/119258209-4f816e80-bbfb-11eb-9f4b-19debbbf0968.png)

**Comment by arenekosreal** [comment]
这似乎是PyQt6-6.1.0更新后的变化，已发布更新，请等待作者合并Pull Request，急用的话可以到我的同名仓库获取`main-gui.py`文件

**Comment by arenekosreal** [comment]
如果解决了问题，请点一下Close issue关闭这个问题
