### ISSUE TITLE
关于uc_token的获取

### ISSUE THREAD

**Issue by Femcatty** [Upsetin/ChinaUniOnline#137]
# 请求帮助

## 目标

请问uc_token每次打开页面都可以抓到吗？我用电脑微信打开，使用wireshark抓包，似乎是因为自动登录的原因，抓不到HTTP GET请求。有什么解决办法吗？

**Comment by arenekosreal** [comment]
正常登进答题页面一次就有了，不过我是在手机上抓的，电脑这边没有看过

**Comment by Femcatty** [comment]
枯辽，我怎么一直自动登录呀，有什么办法强制正常登录一次吗

**Comment by arenekosreal** [comment]
自动登陆也算正常登陆的，只要正常进选择答题项目还有个人页的那个页面就行，在记录里面仔细找找，有时候可能和其他的混在一起不容易看出来。还有就是一定要在打开答题网页之前打开抓包

**Comment by Femcatty** [comment]
> 自动登陆也算正常登陆的，只要正常进选择答题项目还有个人页的那个页面就行，在记录里面仔细找找，有时候可能和其他的混在一起不容易看出来。还有就是一定要在打开答题网页之前打开抓包

咦，是因为https的原因吗🤔 我又检查了几遍，只有与49.233.125.98通信的TCP包和TLS包

**Comment by arenekosreal** [comment]
api是https流量，所以需要安装证书解密https流量才行

**Comment by Femcatty** [comment]
看起来有点麻烦，手机上操作也需要解密https吗？有什么操作简单的方法吗？

**Comment by Femcatty** [comment]
我解决了，去手机上随便下了个软件自带解密https功能，感谢！

**Comment by arenekosreal** [comment]
抓包工具解密https都是通过安装一个证书实现的，电脑反而更简单，手机的话没有root就有点麻烦
