### ISSUE TITLE
可以添加一个刷答题次数的功能

### ISSUE THREAD

**Issue by LRSnowX** [Upsetin/ChinaUniOnline#22]
因为学校不止看分数，还会看答题次数，分数太高次数太少就会被发现正确率高得离谱。自己手动盲选刷答题次数效率又比较低。希望能加一个刷答题次数的功能，进去随机选或者全选c都行

**Comment by arenekosreal** [comment]
GUI模式有，所有模式都可以调整启用状态和答题次数，但安装麻烦一点，得装一些额外的依赖，具体可以进到GUI文件夹查看相关介绍
