### ISSUE TITLE
点击设置闪退

### ISSUE THREAD

**Issue by lengxiaoyu6** [Upsetin/ChinaUniOnline#29]
运行之后点击设置后闪退

**Comment by arenekosreal** [comment]
设置界面我这里使用没有问题，确定已经安装完全部依赖了吗？如果是点击开始后闪退，请确定设置里面已经设置了正确的Token，refresh_token非必须

**Comment by lengxiaoyu6** [comment]
> 设置界面我这里使用没有问题，确定已经安装完全部依赖了吗？如果是点击开始后闪退，请确定设置里面已经设置了正确的Token，refresh_token非必须

依赖是已经装了的，但是点击设置还是会闪退

**Comment by arenekosreal** [comment]
可以看一下Traceback吗，用终端运行`python main-gui.py`执行这个py文件，终端的输出内容是什么

**Comment by lengxiaoyu6** [comment]
![image](https://user-images.githubusercontent.com/43517191/111071550-a7239f80-8511-11eb-8c9c-a4f7f92032a8.png)

**Comment by arenekosreal** [comment]
是不是还在用旧版配置文件？是的话按照最后一个pull request说的加上auth部分或者删掉原来的配置让程序重新生成一份
![image](https://user-images.githubusercontent.com/17194552/111072182-5f524780-8514-11eb-95c3-8968f2e1866e.png)
大概的配置文件应该是这样的，refresh_token和token应该是空字符串“”或者是你抓包捕获到的数据

**Comment by lengxiaoyu6** [comment]
解决了，谢谢

**Comment by arenekosreal** [comment]
解决了麻烦点击一下Comment左边的Close issue以关闭这一项问题，这样可以防止对完成情况造成不必要的误判，谢谢
