### ISSUE TITLE
话说非GUI版还更新吗？

### ISSUE THREAD

**Issue by LRSnowX** [Upsetin/ChinaUniOnline#34]
感觉还是直接在终端里面用起来比较方便 还隐蔽 😂

**Comment by haloowhite** [comment]
会更新的，只不过最近有点忙哈哈哈


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年3月16日(周二) 晚上10:40
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Upsetin/ChinaUniOnline] 话说非GUI版还更新吗？ (#34)




 
感觉还是直接在终端里面用起来比较方便 还隐蔽 
 
&mdash;

**Comment by arenekosreal** [comment]
现在GUI已经加入一个托盘图标，在相关设置打开（默认）后将最小化至系统托盘，不过喜欢终端的话还是慢慢等dalao更新吧😂
