### ISSUE TITLE
感觉效率有点低，刷一波才加30分，老哥能否再优化下呢？

### ISSUE THREAD

**Issue by pipipiper** [Upsetin/ChinaUniOnline#43]
还有就是每刷一会儿就会提示KeyError qustion_ids 请问是什么意思呢？

**Comment by arenekosreal** [comment]
把日志文件发一下吧。太快的话服务器会有警告，所以会在每次答题的时候随机暂停零点几到几秒，完全不暂停的话几乎每次都会出现过快的警告，而且可以在设置里面设置多一点次数，然后把它扔到后台慢慢跑就行，现在最小化到托盘后会在完成任务的时候发送一个通知

**Comment by pipipiper** [comment]
[logs.log](https://github.com/Upsetin/ChinaUniOnline/files/6157347/logs.log)

**Comment by pipipiper** [comment]
你好 这是日志文件 谢谢大佬

**Comment by arenekosreal** [comment]
看文件记录似乎是被服务器踢了，估计是token到期了或者答得太多被制裁了。原因明天再来慢慢查吧，现在可以用一下uid登陆，这个倒肯定可以解决token过期的问题

**Comment by pipipiper** [comment]
不知道是啥情况，我现在就是uid登录，而且这个号才3000分，按理说没有答得很多呀，请大佬再帮忙看看，谢谢啦。

**Comment by Philae994** [comment]
请问uid在哪里抓 user那个链接的id吗

**Comment by pipipiper** [comment]
> 请问uid在哪里抓 user那个链接的id吗

我是用微信x5内核的调试功能抓的

**Comment by arenekosreal** [comment]
> 请问uid在哪里抓 user那个链接的id吗

可以调试x5内核，也可以按照GUI文件夹下的README.md文件的描述拿到

**Comment by arenekosreal** [comment]
> 不知道是啥情况，我现在就是uid登录，而且这个号才3000分，按理说没有答得很多呀，请大佬再帮忙看看，谢谢啦。

偶然间发现了，是刷题的时候又在其他地方登陆导致刷题的这个账号被挤下去了，刷题的时候就不要用微信登陆了，拿到Token就要关掉那个网页。已经在README里面加上这一条注意事项

**Comment by Philae994** [comment]
感谢

**Comment by haloowhite** [comment]
建议试试老版本，现已更新


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年3月18日(周四) 下午4:09
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [Upsetin/ChinaUniOnline] 感觉效率有点低，刷一波才加30分，老哥能否再优化下呢？ (#43)




 
感谢
 
&mdash;

**Comment by arenekosreal** [comment]
如果解决了你的问题，请点一下Close issue关闭这个问题
