### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by missuo** [Upsetin/ChinaUniOnline#44]
Traceback (most recent call last):
  File "main.py", line 336, in <module>
    Login()
  File "main.py", line 312, in Login
    ViewQR(a.json()['data']['qrcode'])
TypeError: 'NoneType' object is not subscriptable

**Comment by arenekosreal** [comment]
https://github.com/Upsetin/ChinaUniOnline/issues/23
用GUI里面的新程序，有一些登陆所需数据获取看网页，终端模式的程序等dalao更新

**Comment by missuo** [comment]
GUI也报错。我一会截图给你。

**Comment by arenekosreal** [comment]
问题还存在吗？如果问题已经解决，请点一下Close issue关闭这个问题
