### ISSUE TITLE
抓包问题

### ISSUE THREAD

**Issue by llllcccjjj** [Upsetin/ChinaUniOnline#47]
# 请求帮助

## 目标

[^_^]: 在这里写你想做什么
我直接利用httpcandy抓包,没找到说的那个网址的uid包
![image](https://user-images.githubusercontent.com/70000656/111579206-92d0f280-87f0-11eb-856b-8f28f64ee329.png)
使用的这个抓的id应该不对.
请问抓包必须要gui那样装平行空间吗

**Comment by arenekosreal** [comment]
有root可以直接抓，微信有一个证书信任规则如下：

1. 安卓系统7.0以下版本，不管微信任意版本，都会信任系统提供的证书
2. 安卓系统7.0以上版本，微信7.0以下版本，微信会信任系统提供的证书
3. 安卓系统7.0以上版本，微信7.0以上版本，微信只信任它自己配置的证书列表

目标地址不是这个，而是目标地址为 https://ssxx.univs.cn/cgi-bin/authorize/token/ 的GET请求记录，看截图的情况应该还要往前面找。

**Comment by IPENCIL666** [comment]
我也是抓不到 https://ssxx.univs.cn/cgi-bin/authorize/token/ 这个url的数据包，文档上说的小程序是啥，我在公众号中的网站打开的

**Comment by arenekosreal** [comment]
小程序也相当于打开这个网页，估计是有浏览器缓存导致没有验证，我看了一下，可以抓 https://ssxx.univs.cn/cgi-bin/portal/user 的包，响应数据也是一个JSON文档，里面的data下的id的值也是UID

**Comment by IPENCIL666** [comment]
> 小程序也相当于打开这个网页，估计是有浏览器缓存导致没有验证，我看了一下，可以抓 https://ssxx.univs.cn/cgi-bin/portal/user 的包，响应数据也是一个JSON文档，里面的ID也是UID

我再试试

**Comment by IPENCIL666** [comment]
> 小程序也相当于打开这个网页，估计是有浏览器缓存导致没有验证，我看了一下，可以抓 https://ssxx.univs.cn/cgi-bin/portal/user 的包，响应数据也是一个JSON文档，里面的data下的id的值也是UID

清除一下微信缓存，就找到了，大佬牛逼
清理微信缓存的方法：https://baijiahao.baidu.com/s?id=1628335200476551849&wfr=spider&for=pc

**Comment by arenekosreal** [comment]
解决了问题麻烦点一下Close issue关闭这一项问题
