### ISSUE TITLE
有没有什么方式让他直接重新开始呀。。。每次这样有点麻烦。。感谢大佬！！！

### ISSUE THREAD

**Issue by JefferyHcool** [Upsetin/ChinaUniOnline#49]
# 请求帮助

## 目标

[^_^]: 在这里写你想做什么

**Comment by JefferyHcool** [comment]
自己重新开始

**Comment by arenekosreal** [comment]
你指的意思是用户可以主动终止答题吗

**Comment by JefferyHcool** [comment]
哈哈，没事，找到了，作者方便给个联系方式吗，我也是最近在学爬虫这一块，想和大佬交流交流，python新手





------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月18日(星期四) 晚上6:18
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Upsetin/ChinaUniOnline] 有没有什么方式让他直接重新开始呀。。。每次这样有点麻烦。。感谢大佬！！！ (#49)





 
你指的意思是用户可以主动终止答题吗

**Comment by arenekosreal** [comment]
解决了就好，麻烦点一下Close issue关闭这项问题。关于联系方式，考虑到这个项目的敏感性，我觉得我不能给你我的联系方式，抱歉。不过这个项目的拥有者那个dalao也许并不介意给你ta的联系方式。关闭这个项目后可以继续发表回复的，python的问题我可以用这种方法尽我所能帮忙。

**Comment by JefferyHcool** [comment]
好的，感谢大佬，麻烦您留个联系方式




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月18日(星期四) 晚上6:25
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Upsetin/ChinaUniOnline] 有没有什么方式让他直接重新开始呀。。。每次这样有点麻烦。。感谢大佬！！！ (#49)





 
解决了就好，麻烦点一下Close issue关闭这项问题。关于联系方式，考虑到这个项目的敏感性，我觉得我不能给你我的联系方式，抱歉。不过这个项目的拥有者那个dalao也许并不介意给你ta的联系方式。关闭这个项目后可以继续发表回复的，python的问题我可以用这种方法尽我所能帮忙。

**Comment by arenekosreal** [comment]
> 好的，感谢大佬，麻烦您留个联系方式
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年3月18日(星期四) 晚上6:25 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [Upsetin/ChinaUniOnline] 有没有什么方式让他直接重新开始呀。。。每次这样有点麻烦。。感谢大佬！！！ (#49) 解决了就好，麻烦点一下Close issue关闭这项问题。关于联系方式，考虑到这个项目的敏感性，我觉得我不能给你我的联系方式，抱歉。不过这个项目的拥有者那个dalao也许并不介意给你ta的联系方式。关闭这个项目后可以继续发表回复的，python的问题我可以用这种方法尽我所能帮忙。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

那个dalao的联系方式写在项目README的，是xiaobaiyeaidaima@gmail.com，我的话直接在这个issue里面回复吧，或者电报[@ZhangHua2333](https://t.me/ZhangHua2333)
