### ISSUE TITLE
main.exe 使用uid无法登录

### ISSUE THREAD

**Issue by dixi12365** [Upsetin/ChinaUniOnline#50]
使用uid登录程序得到返回为 taken已过期。请问这怎么解决

**Comment by Philae994** [comment]
我也是这样 输入token后
已更新token,正在获取信息...
输入token有误或登录已过期...
感谢使用！回车退出程序:)

**Comment by haloowhite** [comment]
token是正常的吗，晚点我看下


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年3月18日(周四) 晚上6:10
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [Upsetin/ChinaUniOnline] main.exe 使用uid无法登录 (#50)




 
我也是这样 输入token后
 已更新token,正在获取信息...
 输入token有误或登录已过期...
 感谢使用！回车退出程序:)
 
&mdash;

**Comment by Philae994** [comment]
> token是正常的吗，晚点我看下
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2021年3月18日(周四) 晚上6:10 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: Re: [Upsetin/ChinaUniOnline] main.exe 使用uid无法登录 (#50) 我也是这样 输入token后 已更新token,正在获取信息... 输入token有误或登录已过期... 感谢使用！回车退出程序:) &mdash; You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

对 刚抓的 用uid和token都不行

**Comment by Philae994** [comment]
File "E:\Pycharm\PyCharm 2020.3.2\plugins\python\helpers\pydev\pydevd.py", line 1477, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "E:\Pycharm\PyCharm 2020.3.2\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/Yinzi/Desktop/ChinaUniOnline-main/main.py", line 473, in <module>
    print('欢迎你，来自%s的%s,当前积分:%s'%(info['university_name'],info['name'],info['integral']))
NameError: name 'info' is not defined

**Comment by dixi12365** [comment]
好像可以使用cooike登录

**Comment by haloowhite** [comment]
已更新uid登录问题，相应的py、exe文件都已更新
