### ISSUE TITLE
显示token有误或登录已过期，小白，不知道是不是操作有误

### ISSUE THREAD

**Issue by hkreporters** [Upsetin/ChinaUniOnline#52]
# 请求帮助

## 目标

[^_^]: 在这里写你想做什么
另，token后有一段"sign_in_result":false,

**Comment by hkreporters** [comment]
uid登陆可用

**Comment by haloowhite** [comment]
复制token的时候，双引号别一起复制进去了哦

**Comment by v-blood** [comment]
怎么抓包啊，token或者uid字段在哪里？我想用wireshake抓包，但是抓了一堆，我不知道怎么过滤

**Comment by hkreporters** [comment]
> 复制token的时候，双引号别一起复制进去了哦
已解决，谢大佬

**Comment by arenekosreal** [comment]
解决了请点击一下Close issue关闭这个问题
