### ISSUE TITLE
题库问题

### ISSUE THREAD

**Issue by Originsin** [Upsetin/ChinaUniOnline#55]
# 请求帮助

## 目标

[^_^]: 网盘下载的文件中题库有问题，许多问题都没有，请教大佬应该怎么办

**Comment by arenekosreal** [comment]
两个程序都会自己捕获未知问题的答案并记录到题库里面，GUI不带初始题库，可自行生成

**Comment by arenekosreal** [comment]
解决了你的问题麻烦点一下Close issue关闭这个问题

**Comment by 598889904** [comment]
OK
