### ISSUE TITLE
其实你可以 吧虚拟环境一下打包成exe的

### ISSUE THREAD

**Issue by rezochs** [Upsetin/ChinaUniOnline#59]
使用那个exe打包 的只要加上 -F --onefile 即可打包 所以依赖

**Comment by haloowhite** [comment]
依赖都打包了的


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年3月22日(周一) 下午2:11
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Upsetin/ChinaUniOnline] 其实你可以 吧虚拟环境一下打包成exe的 (#59)




 
使用那个exe打包 的只要加上 -F --onefile 即可打包 所以依赖
 
&mdash;

**Comment by arenekosreal** [comment]
解决了你的问题吗？解决了请点一下Close issue关闭这一个问题
