### ISSUE TITLE
HttpCanary无法使用

### ISSUE THREAD

**Issue by someonewating** [Upsetin/ChinaUniOnline#60]
# 请求帮助

## 目标

[^_^]: 在这里写你想做什么

安卓11，HttpCanary打开后就是白屏，后闪退。此外，HttpCanary无法在Google play上成功下载，能否为在下提供一个地址？感谢。

**Comment by haloowhite** [comment]
建议在电脑微信上抓包


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年3月22日(周一) 晚上10:45
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Upsetin/ChinaUniOnline] HttpCanary无法使用 (#60)




 
请求帮助
 
目标
 
安卓11，HttpCanary打开后就是白屏，后闪退。此外，HttpCanary无法在Google play上成功下载，能否为在下提供一个地址？感谢。
 
&mdash;

**Comment by someonewating** [comment]
> 建议在电脑微信上抓包
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2021年3月22日(周一) 晚上10:45 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [Upsetin/ChinaUniOnline] HttpCanary无法使用 (#60) 请求帮助 目标 安卓11，HttpCanary打开后就是白屏，后闪退。此外，HttpCanary无法在Google play上成功下载，能否为在下提供一个地址？感谢。 &mdash; You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

谢谢你的回复。请问电脑抓包应该用什么软件呢？我这边使用了Charles，没有成功。

**Comment by kihua** [comment]
> > 建议在电脑微信上抓包
> > […](#)
> > ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2021年3月22日(周一) 晚上10:45 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [Upsetin/ChinaUniOnline] HttpCanary无法使用 (#60) 请求帮助 目标 安卓11，HttpCanary打开后就是白屏，后闪退。此外，HttpCanary无法在Google play上成功下载，能否为在下提供一个地址？感谢。 &mdash; You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> 谢谢你的回复。请问电脑抓包应该用什么软件呢？我这边使用了Charles，没有成功。

fidder，charles均可抓包，百度相关基础设置，抓包URLhttps://ssxx.univs.cn/cgi-bin/portal/race/mode/，即可

**Comment by someonewating** [comment]
> > > 建议在电脑微信上抓包
> > > […](#)
> > > ---原始邮件--- 发件人: _**@**_._**> 发送时间: 2021年3月22日(周一) 晚上10:45 收件人: _**@**_.**_>; 抄送: _**@**_.***>; 主题: [Upsetin/ChinaUniOnline] HttpCanary无法使用 (#60) 请求帮助 目标 安卓11，HttpCanary打开后就是白屏，后闪退。此外，HttpCanary无法在Google play上成功下载，能否为在下提供一个地址？感谢。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> > 
> > 
> > 谢谢你的回复。请问电脑抓包应该用什么软件呢？我这边使用了Charles，没有成功。
> 
> fidder，charles均可抓包，百度相关基础设置，抓包URLhttps://ssxx.univs.cn/cgi-bin/portal/race/mode/，即可

好的，感谢你的回复和帮助。

**Comment by arenekosreal** [comment]
解决了问题麻烦点一下Close issue关闭这一项问题，谢谢
