### ISSUE TITLE
安卓11无法用黄鸟

### ISSUE THREAD

**Issue by AAA-obj** [Upsetin/ChinaUniOnline#61]
# 请求帮助

## 目标

[^_^]: 在这里写你想做什么
大佬出一个电脑抓微信token的教程吧，安卓11用户太难了，球球了，现在学校要求每周500分，要了我的老命

**Comment by arenekosreal** [comment]
电脑可以试试Fiddler之类的抓包工具，我没有亲自试过。而且除了HttpCanary应该还有其他的抓包方案，不过我自己倒没怎么研究了

**Comment by AAA-obj** [comment]
我用了charles，抓不到包，不会用

**Comment by AAA-obj** [comment]
> 电脑可以试试Fiddler之类的抓包工具，我没有亲自试过。而且除了HttpCanary应该还有其他的抓包方案，不过我自己倒没怎么研究了

我用了charles，抓到了包不会用

**Comment by AAA-obj** [comment]
> 电脑可以试试Fiddler之类的抓包工具，我没有亲自试过。而且除了HttpCanary应该还有其他的抓包方案，不过我自己倒没怎么研究了

token是不是ey开头的一长串字符，然后我把token输进去后他提示token已更新，然后就闪退了，

**Comment by arenekosreal** [comment]
> > 电脑可以试试Fiddler之类的抓包工具，我没有亲自试过。而且除了HttpCanary应该还有其他的抓包方案，不过我自己倒没怎么研究了
> 
> token是不是ey开头的一长串字符，然后我把token输进去后他提示token已更新，然后就闪退了，

对的，闪退后终端留下的输出内容是什么呢？GUI程序的话可以试着在设置里面打开调试模式，然后再次执行，看看出问题的时候日志输出什么

**Comment by AAA-obj** [comment]
> > > 电脑可以试试Fiddler之类的抓包工具，我没有亲自试过。而且除了HttpCanary应该还有其他的抓包方案，不过我自己倒没怎么研究了
> > 
> > 
> > 令牌是不是ey开头的一长串字符，然后我把令牌注入进去后他提示token已更新，然后就闪退了，
> 
> 对的，闪退后终端留下的输出内容是什么呢？GUI程序的话可以试着在设置里面打开调试模式，然后再次执行，看看出问题的时候日志输出什么

解决了，应该是网络问题，刷的时候开着代理软件，把代理软件关了就可以刷了，感谢大佬，膜拜
