### ISSUE TITLE
速度问题

### ISSUE THREAD

**Issue by Originsin** [Upsetin/ChinaUniOnline#63]
# 请求帮助
现在软件一次运行速度变慢了，是我的原因还是网页的原因
## 目标

[^_^]: 在这里写你想做什么

**Comment by arenekosreal** [comment]
是GUI程序吗？GUI我最近加了几个随机休眠以规避服务器的答题过快的警告。

**Comment by arenekosreal** [comment]
如果这解决了你的问题，麻烦点一下Close issue关闭这个问题
