### ISSUE TITLE
关于刷分的分数问题

### ISSUE THREAD

**Issue by chenkehao1998** [Upsetin/ChinaUniOnline#64]
想问下这个，每天分数是有上限的吗？好像我后面几次分数没有变过

**Comment by chenkehao1998** [comment]
我中途退出了软件之后 去微信里面查看分数 好像是脚本里面的分数显示不正确！

**Comment by haloowhite** [comment]
不是有提示么？&nbsp;&nbsp;分数本来就有延迟的


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年3月24日(周三) 下午4:14
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [Upsetin/ChinaUniOnline] 关于刷分的分数问题 (#64)




 
我中途退出了软件之后 去微信里面查看分数 好像是脚本里面的分数显示不正确！
 
&mdash;

**Comment by chenkehao1998** [comment]
ok
