### ISSUE TITLE
答题点哪个篇都会闪退

### ISSUE THREAD

**Issue by 1505194659** [Upsetin/ChinaUniOnline#68]
# Bug报告

## 脚本类型

[^_^]:使用的是原版还是GUI版本  原版

## 问题描述

[^_^]:遇到了什么问题

## Python版本3.8.7

[^_^]:正在使用的Python版本3.8.7

## Pip安装的软件包

```text
终端执行 pip list 可查看，将内容复制替换这一行文字
 
```

## 操作系统

[^_^]:是Windows还是Linux或者OSX以及是32位系统还是64位系统

## 终端输出  

```shell

在这里把终端输出的内容粘贴过来，替换这一行文字


```

## 日志文件

```text

在这里粘贴日志文件内容，替换这一行文字


```

**Comment by 1505194659** [comment]
响应内容：
HTTP/1.1 200 OK
Date: Thu, 25 Mar 2021 00:18:19 GMT
Content-Type: application/json; charset=UTF-8
Content-Length: 77
Connection: keep-alive
Server: 12345abc
Etag: "b7b91dd34d9d88198128aa28047d31e06e33c4b9"
Vary: Accept-Encoding
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET

{"code": 4832, "msg": "Greater than the join threshold.", "status_code": 200}

**Comment by arenekosreal** [comment]
原版只有单人的英雄篇支持刷题，输入登陆信息后就会要求输入刷题次数，并且不要在刷题的时候将账号登陆其他设备，要不然脚本会被后面登陆的设备挤下去

**Comment by moeshin** [comment]
这是刷太快了，短时间内刷 4000 分左右就会这个问题。过会就好

**Comment by 1505194659** [comment]
enm。。。俩天还是进不去

**Comment by arenekosreal** [comment]
正常答题有问题吗

**Comment by 1505194659** [comment]
有问题还是点哪个篇都点不进去

**Comment by arenekosreal** [comment]
我指的是在微信正常答题😂

**Comment by 1505194659** [comment]
从抓包响应数据来看超过加入限制阀值

**Comment by 1505194659** [comment]
> 我指的是在微信正常答题😂

> 嗯就是微信正常答题进不去~~~~😱

**Comment by arenekosreal** [comment]
感觉像是账号被查了？试过用新账号登陆吗？

**Comment by 1505194659** [comment]
> 感觉像是账号被查了？试过用新账号登陆吗？
应该是软封了，我改一下代码自己加个休眠机制吧，他的限制阀值应该只的是短时间内的分数快速变化或答题数的增加吧😄

**Comment by 1505194659** [comment]
现在的分数的话在3966

**Comment by arenekosreal** [comment]
每次答题加一个0.1-0.3秒的休眠应该就行了，GUI里面已经有这个机制了，原版程序的话麻烦等一下dalao更新吧

**Comment by arenekosreal** [comment]
今天研究党史答题的时候触发了一样的问题，这是因为党史答题每天只有1次机会。

**Comment by arenekosreal** [comment]
如果你的问题就是这个原因并通过介绍解决了这个问题，请点一下Close issue关闭这一项问题
