### ISSUE TITLE
输入uid回车后闪退

### ISSUE THREAD

**Issue by qq1050175540** [Upsetin/ChinaUniOnline#71]
# 请求帮助

## 目标

[^_^]: 在这里写你想做什么

**Comment by arenekosreal** [comment]
麻烦发一下终端输出，谢谢。

**Comment by qq1050175540** [comment]
> 麻烦发一下终端输出，谢谢。

不好意思啊，我不知道什么是终端输出，我没有学过相关知识

**Comment by arenekosreal** [comment]
你用的是exe文件还是py文件？exe的话没有显示终端，麻烦下一下py文件在命令提示符里面用python执行，这样的话就会有终端输出了

**Comment by qq1050175540** [comment]
> 你用的是exe文件还是py文件？exe的话没有显示终端，麻烦下一下py文件在命令里面里面python执行，这样的话就会有终端输出了

我用的是exe文件，main.py打不开

**Comment by arenekosreal** [comment]
那个需要自己安装Python才行，官网 www.python.org ，慢的话可以到淘宝的镜像 http://npm.taobao.org/mirrors/python/3.9.2/ 去下载，装完了在命令提示符里面运行`pip install requests -i https://mirrors.cloud.tencent.com/pypi/simple` 安装依赖，再在提示符里面运行`python main.py`就可以了

**Comment by qq1050175540** [comment]
> 那个需要自己安装Python才行，官网[www.python.org](http://www.python.org)，慢的话可以到淘宝的附属http://npm.taobao.org/mirrors/python/3.9.2/去下载，装完了在命令里面运行`pip install requests -i https://mirrors.cloud.tencent.com/pypi/simple`安装依赖，再在发展中国家里面运行`python main.py`就可以了

谢谢你的耐心回复，我已经找到闪退的原因：我的uid输入错误。我按照你的方法下载了python，并用python打开了main.python，但是我不知道终端输出在哪。没有问题了，再次谢谢。

**Comment by arenekosreal** [comment]
终端输出就是用Python执行了脚本之后命令提示符的内容😂
不管怎么说，解决了问题就好，麻烦点一下Close issue关闭这一项问题
