### ISSUE TITLE
怎样解决速度问题 刚开始5分钟500分 现在3分钟20分

### ISSUE THREAD

**Issue by H0121** [Upsetin/ChinaUniOnline#80]
# 请求帮助

## 目标

[^_^]: 在这里写你想做什么
xxxxxx

**Comment by arenekosreal** [comment]
是GUI的程序还是原版程序

**Comment by H0121** [comment]
> 是GUI的程序还是原版程序

原版程序 用的pycharm

**Comment by arenekosreal** [comment]
https://github.com/Upsetin/ChinaUniOnline/issues/79
看看是不是和这个问题的内容接近，如果是的话麻烦保持关注一下这个问题，我们会主要在这个问题里面讨论可能的解决方法

**Comment by lws1073659753** [comment]
同求现在速度慢了不少

**Comment by wxin996** [comment]
慢了不少

**Comment by lws1073659753** [comment]
慢的问题可以解决下吗

**Comment by lws1073659753** [comment]
@zhanghua000

**Comment by arenekosreal** [comment]
麻烦关注一下提到的那个相似问题。由于原问题提问者没有继续给出相关数据，可以麻烦一下你去测量一下时间吗？我这里运行速度倒是没什么问题，不能测出有意义的结果。

**Comment by lws1073659753** [comment]
下的解压包里面打开的现在刷一遍得一分钟





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Upsetin/ChinaUniOnline"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月31日(星期三) 下午4:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Upsetin/ChinaUniOnline] 怎样解决速度问题 刚开始5分钟500分 现在3分钟20分 (#80)





 
麻烦关注一下提到的那个相似问题。由于原问题提问者没有继续给出相关数据，可以麻烦一下你去测量一下时间吗？我这里运行速度倒是没什么问题，不能测出有意义的结果。

**Comment by lws1073659753** [comment]
这里面发不了图片

**Comment by lws1073659753** [comment]
现在刷一遍得一两分钟
![image](https://user-images.githubusercontent.com/81338285/113120969-bb230d00-9244-11eb-8d31-8dec49f82e7b.png)

**Comment by arenekosreal** [comment]
不是这个时间，请按照[这里](https://blog.csdn.net/leviopku/article/details/106651069)的方法对文件`main.py`进行修改并使用Python执行它，这样来确定函数的执行时间，请分别确认文件第192行的Confire，第119行的GetOption以及117行和304行的SubmitVerification这四处共三个函数的执行时间。这需要你对Python有一定的了解。

**Comment by lws1073659753** [comment]
Python不会有没有别的解决办法啊

**Comment by arenekosreal** [comment]
不会的话就得等其他人来处理了，在这段时间里面可以使用GUI文件夹里面的程序应急，由于我并没有提供exe程序且脚本里面部分变量导致exe打包可能存在问题，这仍然需要你手动安装Python及相关依赖。
你可以到[这里](http://npm.taobao.org/mirrors/python/3.9.2/python-3.9.2.exe)下载Python并完成安装，注意需要保证“将Python添加到PATH”这个选项被选中。安装完成后按下Win+R，在运行对话框里面输入cmd并按下Enter键，在弹出的叫做“命令提示符”的新窗口里面输入`pip install -r `（最后有一个英文空格）并粘贴GUI文件夹的`requirements.txt`文件的位置。你可以通过把这个文件拖动到命令提示符窗口完成位置的粘贴。在粘贴完成位置后请在后面加一个` -i https://mirrors.cloud.tencent.com/pypi/simple`（最开始有一个英文空格），这样最后的字符串应该类似于这样：
`pip install -r "D:\D盘\中国大学生在线答题\ChinaUniOnline-main\ChinaUniOnline-main\GUI\requirements.txt" -i https://mirrors.cloud.tencent.com/pypi/simple`
并按下Enter键，等待命令执行完成后就可以到GUI文件夹内双击`start.vbs`完成启动，以后只需要运行`start.vbs`就行了

**Comment by lws1073659753** [comment]
打不开
![Uploading image.png…]()

**Comment by lws1073659753** [comment]
打不开
![image](https://user-images.githubusercontent.com/81338285/113137782-8e2c2580-9257-11eb-8427-d6754ab510ee.png)

**Comment by arenekosreal** [comment]
具体是怎么个打不开的情况

**Comment by arenekosreal** [comment]
程序路径里面不要有中文，类似的问题都是安装位置太特殊。再不行的话用pip卸载PyQt6并重装一下试试

**Comment by H0121** [comment]
> 同求现在速度慢了不少

早上起来 速度要快很多
