### ISSUE TITLE
救救孩子，孩子题库读不进去了

### ISSUE THREAD

**Issue by OhhhhToodles** [Upsetin/ChinaUniOnline#82]
# 请求帮助

## 如图
![)62VVX 8KU32M_ NN)DBN2](https://user-images.githubusercontent.com/60874276/112972024-64ed9580-9182-11eb-862b-5af45818f1b7.png)
![{O%GH@Z8KF~NWHNG`KU )DI](https://user-images.githubusercontent.com/60874276/112972047-6a4ae000-9182-11eb-83fc-1b06e3805184.png)
求助！！

**Comment by haloowhite** [comment]
把题库文件名改成绝对路径


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年3月30日(周二) 晚上6:05
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Upsetin/ChinaUniOnline] 救救孩子，孩子题库读不进去了 (#82)




 
请求帮助
 
如图
 

 
 求助！！
 
&mdash;

**Comment by OhhhhToodles** [comment]
hhh，谢谢，我感觉我又可以了

**Comment by arenekosreal** [comment]
解决了问题麻烦点一下Close issue关闭这个问题

**Comment by OhhhhToodles** [comment]
现在关了吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月30日(星期二) 晚上6:56
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Upsetin/ChinaUniOnline] 救救孩子，孩子题库读不进去了 (#82)





 
解决了问题麻烦点一下Close issue关闭这个问题
 
—
您收到此消息是因为您创建了线程。
直接回复此电子邮件，在GitHub上查看，或取消订阅。
