### ISSUE TITLE
打开可执行文件会闪退

### ISSUE THREAD

**Issue by Fitye** [Upsetin/ChinaUniOnline#84]
# 请求帮助main.exe打开输入token敲击回车键后会闪退，无法正常运行

## 目标

[^_^]: 在这里写你想做什么
xxxxxx

**Comment by arenekosreal** [comment]
token格式不对，可能多了几个空格或者少了结尾的字符什么的。建议直接用uid登陆

**Comment by arenekosreal** [comment]
如果问题解决，请点一下Close issue关闭这个问题
