### ISSUE TITLE
关于抢十赛

### ISSUE THREAD

**Issue by Wuliannan-6** [Upsetin/ChinaUniOnline#88]
没错，又是我

今天仔细看了一下日志，发现抢十赛答对了15道题。但是抢十赛的规则是答对10题就应该结束了。
GUI程序里抢十赛强制答完了30题（无论期间答对多少题），时间也算的是答30题的时间。

这个特性有没有办法修改呢😂

**Comment by arenekosreal** [comment]
啊这。。。我仿照英雄篇的逻辑写的，说来惭愧，我现在连抢十赛网页是啥样都不知道😂等这几个严重点的问题解决了再来处理吧

**Comment by Wuliannan-6** [comment]
哈哈哈哈，感谢。昨天分数归零的问题解决了，再次点击开始也可以继续执行了，但在不开启用户信息显示的情况下还是会闪退（其实我觉得这个问题不大）

**Comment by arenekosreal** [comment]
现在抢十赛应该能够在正确答题10道时就可以结束了

**Comment by Wuliannan-6** [comment]
测试了一下，偶尔会遇到抢十赛答了30题的同道中人😂但是只要答对10题时间比他短好像还是会给加分。
谢谢大佬
