### ISSUE TITLE
token获取网站被关闭

### ISSUE THREAD

**Issue by someonewating** [Upsetin/ChinaUniOnline#98]
现在获取token的网站被关闭了，

> 很抱歉，您提交的请求可能对网站造成威胁，请求已被管理员设置的策略阻断
> 如何解决：
> 
> 本页面为腾讯云T-Sec Web应用防火墙(WAF)默认提示页面，如有疑问请联系网站管理员并提供UUID信息

请问各位有什么解决方案吗？

**Comment by arenekosreal** [comment]
UID登陆，或者自己抓包分析找Token，方法就在仓库README里面。UID目前为止一次设置就不用管了，可以一直用。
有个叫i呀我去的公众号的四史问答Go可以拿UID和Token，不建议用他的云端刷，毕竟人家资源不多，现在已经吃紧了
差点以为Token不能登陆了，吓我一跳😂

**Comment by arenekosreal** [comment]
解决了问题的话麻烦点一下Close issue关闭这个问题

**Comment by someonewating** [comment]
> UID登陆，或者自己抓包分析找Token，方法就在仓库README里面。UID目前为止一次设置就不用管了，可以一直用。
> 有个叫i呀我去的公众号的四史问答Go可以拿UID和Token，不建议用他的云端刷，毕竟人家资源不多，现在已经吃紧了
> 差点以为Token不能登陆了，吓我一跳😂

谢谢你的回复。也谢谢你提供的方法。
