### ISSUE TITLE
GUI版本登录有点问题

### ISSUE THREAD

**Issue by Uc207Pr4f57t9-251** [Upsetin/ChinaUniOnline#99]
# GUI版本不太会用
## 能登录上刷题就行
电脑是win10，也安装了requirements，在编译执行gui版本后在设置中输入了uid，token和更新token（不知道要不要都输入，不太会用），之后也设置了要刷的模块，就报错了。
Traceback (most recent call last):
  File "I:\programs\ChinaUniOnline-main\GUI\main-gui.py", line 935, in start
    self.processor=TestProcessor(query=self.query,show_qr_signal=self.show_qr_signal,close_qr_signal=self.close_qr_signal,user_info_signal=self.user_info_signal,update_info_signal=self.update_info_signal,prefix="ssxx")
  File "I:\programs\ChinaUniOnline-main\GUI\main-gui.py", line 306, in __init__
    self.login()
  File "I:\programs\ChinaUniOnline-main\GUI\main-gui.py", line 342, in login
    self.login(type_="v0")
  File "I:\programs\ChinaUniOnline-main\GUI\main-gui.py", line 439, in login
    self.expire=self.decode_token()[self.token.split(".")[1]]["exp"]
IndexError: list index out of range
看起来好像是登录有问题？

**Comment by arenekosreal** [comment]
Token解码出现了问题。试试只输UID可以登陆吗

**Comment by Uc207Pr4f57t9-251** [comment]
也不行。。。

**Comment by arenekosreal** [comment]
你输入的UID是一个24位的字符串吗
像这样
![image](https://user-images.githubusercontent.com/17194552/114271421-d3183f00-9a43-11eb-96fb-3a646746cfeb.png)
如果还有问题的话麻烦私发一下UID到我主页的邮箱里面，我帮你看看

**Comment by Uc207Pr4f57t9-251** [comment]
是的，我发给你你看看

**Comment by zhanghua000** [comment]
我这里测试了一下，UID登陆没有问题

**Comment by arenekosreal** [comment]
![image](https://user-images.githubusercontent.com/17194552/114272436-c77b4700-9a48-11eb-869c-cca653191815.png)
UID登陆没有问题，我觉得你应该检查一下你的网络

**Comment by Uc207Pr4f57t9-251** [comment]
我把vpn全都关了，也没有用代理了，用自己的手机的热点，但是还是报错登录错误
Traceback (most recent call last):
  File "I:\programs\ChinaUniOnline-main\GUI\main-gui.py", line 935, in start
    self.processor=TestProcessor(query=self.query,show_qr_signal=self.show_qr_signal,close_qr_signal=self.close_qr_signal,user_info_signal=self.user_info_signal,update_info_signal=self.update_info_signal,prefix="ssxx")
  File "I:\programs\ChinaUniOnline-main\GUI\main-gui.py", line 306, in __init__
    self.login()
  File "I:\programs\ChinaUniOnline-main\GUI\main-gui.py", line 342, in login
    self.login(type_="v0")
  File "I:\programs\ChinaUniOnline-main\GUI\main-gui.py", line 322, in login
    def login(self,keep_referer:bool=False,type_:str="v1"):
IndexError: list index out of range
Press any key to continue . . .

Schwarzer

发件人: zhanghua000
发送时间: 2021年4月10日 下午 10:08
收件人: Upsetin/ChinaUniOnline
抄送: Uc207Pr4f57t9-251; Author
主题: Re: [Upsetin/ChinaUniOnline] GUI版本登录有点问题 (#99)


UID登陆没有问题，我觉得你应该检查一下你的网络

**Comment by Uc207Pr4f57t9-251** [comment]
这个是我的log
2021-04-10 22:11:01-INFO-使用网页OAuth登陆
2021-04-10 22:11:01-INFO-正在获取二维码
2021-04-10 22:11:02-ERROR-登陆出错
2021-04-10 22:11:02-INFO-使用存储的登陆信息完成登陆
2021-04-10 22:11:02-ERROR-Token置登陆所需UID或者Token

Schwarzer

发件人: zhanghua000
发送时间: 2021年4月10日 下午 10:08
收件人: Upsetin/ChinaUniOnline
抄送: Uc207Pr4f57t9-251; Author
主题: Re: [Upsetin/ChinaUniOnline] GUI版本登录有点问题 (#99)


UID登陆没有问题，我觉得你应该检查一下你的网络

**Comment by arenekosreal** [comment]
![image](https://user-images.githubusercontent.com/17194552/114272802-2bead600-9a4a-11eb-8dc7-8f41a5855a13.png)
麻烦到脚本的436行对照这张图将下面的内容加入进去，然后在设置里面打开调试模式，把程序日志发一下
内容：
```python
self.logger.debug("服务器回复：%s" %json_response)
self.logger.debug("获取Token:%s" %self.token)
self.logger.debug("获取Refresh Token：%s" %self.refresh_token)
```

**Comment by arenekosreal** [comment]
考虑到敏感信息，你可能仍然需要发邮件过来

**Comment by Uc207Pr4f57t9-251** [comment]
我添加了，

但是不太清楚这个按钮是蓝色的是启用还是偏灰色的是启用，我是先这样设置了

如果可以把按钮启用是蓝色禁用是红色就更好了（小声）
输出是
2021-04-10 22:26:03-INFO-使用网页OAuth登陆
2021-04-10 22:26:03-INFO-正在获取二维码
2021-04-10 22:26:03-ERROR-登陆出错
2021-04-10 22:26:03-INFO-使用存储的登陆信息完成登陆
2021-04-10 22:26:03-ERROR-Token置登陆所需UID或者Token
（感觉跟之前的没差？）
Schwarzer

发件人: zhanghua000
发送时间: 2021年4月10日 下午 10:18
收件人: Upsetin/ChinaUniOnline
抄送: Uc207Pr4f57t9-251; Author
主题: Re: [Upsetin/ChinaUniOnline] GUI版本登录有点问题 (#99)


麻烦到脚本的436行对照这张图将下面的内容加入进去，然后在设置里面打开调试模式，把程序日志发一下
内容：
self.logger.debug("服务器回复：%s" %json_response)

self.logger.debug("获取Token:%s" %self.token)

self.logger.debug("获取Refresh Token：%s" %self.refresh_token)

**Comment by Uc207Pr4f57t9-251** [comment]
请问您是否有telegram或者qq之类的联系手段？

Schwarzer

发件人: zhanghua000
发送时间: 2021年4月10日 下午 10:18
收件人: Upsetin/ChinaUniOnline
抄送: Uc207Pr4f57t9-251; Author
主题: Re: [Upsetin/ChinaUniOnline] GUI版本登录有点问题 (#99)


麻烦到脚本的436行对照这张图将下面的内容加入进去，然后在设置里面打开调试模式，把程序日志发一下
内容：
self.logger.debug("服务器回复：%s" %json_response)

self.logger.debug("获取Token:%s" %self.token)

self.logger.debug("获取Refresh Token：%s" %self.refresh_token)

**Comment by arenekosreal** [comment]
浅色代表未启用。从日志看起来没有DEBUG级的日志，应该是没有启用调试模式的。外观这个我没有啥设计经验，当初就顺手拿生成器生成的一组颜色😂可以用记事本直接打开`config.json`，找到debug这一项，把它的值由false改成true就行了

**Comment by arenekosreal** [comment]
电报可以找@zhanghua2333 头像是香子兰的头像，加我的话麻烦说一下原因

**Comment by Uc207Pr4f57t9-251** [comment]
电报已经找到了

Schwarzer

发件人: zhanghua000
发送时间: 2021年4月10日 下午 10:54
收件人: Upsetin/ChinaUniOnline
抄送: Uc207Pr4f57t9-251; Author
主题: Re: [Upsetin/ChinaUniOnline] GUI版本登录有点问题 (#99)

***@***.*** 头像是香子兰的头像，加我的话麻烦说一下原因

**Comment by arenekosreal** [comment]
好的，我已经发消息了
